:bastion_ssh_user_name: %bastion_ssh_user_name%
:bastion_public_hostname: %bastion_public_hostname%
:aap_controller_web_url: %aap_controller_web_url%
:aap_controller_admin_user: %aap_controller_admin_user%
:aap_controller_admin_password: %aap_controller_admin_password%
:aap_controller_admin_token: %aap_controller_admin_token%
:openshift_api_url: %openshift_api_url%
:openshift_token: %openshift_token%
:format_cmd_exec: source,options="nowrap",,role="copy",subs="{markup-in-source}"



== Introduction to Ansible Rulebooks

In this exercise, you will learn how to write an Ansible Rulebook, which is a
set of instructions that connects events to actions. You will be provided
with an Ansible playbook that handles PVC (Persistent Volume Claim) and
VolumeSnapshot creation. 

Your task is to create a rulebook that triggers an Ansible Job within automation
controller using specific event variables.

== Prerequisites 

* Access to your Bastion Host Credentials
* Access to your controller admin token
* Access to the automation controller dashboard
* SSH capabilities to the Bastion Host via terminal
* Access to the Git repository, demos, with the exercises
* Installation of the Ansible Rulebook container image via `podman`

=== Access the Bastion Host

Using the bastion host credentials, `ssh` into the host:

[{format_cmd_exec}]
----
$ ssh {bastion_ssh_user_name}@{bastion_public_hostname}
----

=== Git repository

With access to the bastion host, clone the Git repository with the exercises
for the lab. They are located under https://github.com/rlopez133/demos

[{format_cmd_exec}]
----
$ git clone https://github.com/rlopez133/demos
----

[NOTE]
====
All the exercises for this lab will be found under the `demos/eda_ocp`
directory. There is a folder associated for each exercise.
====

=== Install the Ansible Rulebook podman image

Within the bastion host, pull the container image for the Ansible Rulebook via

[{format_cmd_exec}]
----
$ podman pull quay.io/ansible/ansible-rulebook:v0.12.0
----

This will be used to run the Ansible Rulebooks without the need to install
Ansible Rulebooks directly on the bastion host.

=== Access automation controller dashboard

Via a browser, ensure you can access the automation controller dashboard.

URL: {aap_controller_web_url}

username: {aap_controller_admin_user}

password: {aap_controller_admin_password}

== Understanding the Provided Ansible Playbook

The provided Ansible playbook, `pvc_snapshot_playbook.yml`, automates the
process of creating a VolumeSnapshot for a newly added Persistent Volume Claim
(PVC) in a OpenShift cluster. The playbook consists of a series of tasks
ensuring the Persistent Volume Claim gets created and provides details on the
Volume Snapshot.

The Ansible playbook contains four tasks:

* The first task waits for a PVC to enter the "Bound" status. It uses the `kubernetes.core.k8s_info` module to gather information about the PVC, based on the event's namespace and name. The task will keep retrying until the PVC reaches the "Bound" status or the maximum number of retries is reached.  

* The second task creates a VolumeSnapshot using the `kubernetes.core.k8s` module. This task will only execute if the PVC is in the "Bound" status.  The rescue section contains error handling and debugging tasks. If the PVC fails to reach the "Bound" status, the rescue section will be executed, providing debug information and a message that the PVC never achieved the "Bound" status.

* The third task retrieves the details of a Kubernetes VolumeSnapshot resource using the `kubernetes.core.k8s_info` module.

* The fourth task prints the name and namespace of each VolumeSnapshot retrieved in the previous task using the `ansible.builtin.debug` module 


.Ansible PVC Playbook
----
---
- name: Ansible Playbook for PVC and VolumeSnapshot
  hosts: localhost
  connection: local
  gather_facts: yes
  collections:
    - community.general
  tasks:
    - name: Block to handle PVC and VolumeSnapshot
      block:
        - name: Wait for Persistent Volume Claim to be Bound
          kubernetes.core.k8s_info:
            kind: PersistentVolumeClaim
            namespace: "{{ ansible_eda.event.resource.metadata.namespace }}"
            name: "{{ ansible_eda.event.resource.metadata.name }}"
          register: pvc_status
          until: pvc_status.resources | default([]) | length > 0 and pvc_status.resources[0].status.phase == "Bound"
          retries: 5
          delay: 10

        - name: Create VolumeSnapshot
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: snapshot.storage.k8s.io/v1
              kind: VolumeSnapshot
              metadata:
                name: "{{ ansible_eda.event.resource.metadata.name }}-snapshot-{{ ansible_date_time.date }}"
                namespace: "{{ ansible_eda.event.resource.metadata.namespace }}"
              spec:
                source:
                  persistentVolumeClaimName: "{{ ansible_eda.event.resource.metadata.name }}"
          when: pvc_status.resources[0].status.phase == "Bound"

      rescue:

        - name: event debug
          ansible.builtin.debug:
            var: pvc_status

        - name: Debug status
          ansible.builtin.debug:
            msg: "{{ pvc_status.resources[0].status.phase }}"

        - name: Handle PVC not Bound
          ansible.builtin.debug:
            msg: "Status 'Bound' was never achieved for the Persistent Volume Claim {{ ansible_eda.event.resource.metadata.name }}"

    - name: Get VolumeSnapshot details
      kubernetes.core.k8s_info:
        api_version: snapshot.storage.k8s.io/v1
        kind: VolumeSnapshot
        namespace: "{{ ansible_eda.event.resource.metadata.namespace }}"
      register: volumesnapshot_details

    - name: Debug message for VolumeSnapshot name and namespace
      ansible.builtin.debug:
        msg: "Name: {{ item.name }}, Namespace: {{ item.namespace }}"
      loop: "{{ volumesnapshot_details | community.general.json_query('resources[*].metadata') }}"
      loop_control:
        label: "Name: {{ item.name }}, Namespace: {{ item.namespace }}"
----

== Writing the Ansible Rulebook

In this section, you will be provided with an example rulebook. Your task is to
modify the example rulebook to run the Ansible Job Template
`EDA-OpenShift-Exercise1` when a `PersistentVolumeClaim` gets created.

[{format_cmd_exec}]
.Example Rulebook
----
- name: Example Rulebook
  hosts: all
  sources:
    - my_event_source:
        api_version: v1
        kind: SomeResource
  rules:
    - name: Perform Action
      condition: event.type == "SOME_EVENT"
      action:
        run_job_template:
          name: Example-Job-Template
          organization: Default
----

Follow these steps to modify the example rulebook:

. Copy the example rulebook to a file named `exercise1-rulebook.yml` within the /path/to/demos/eda_ocp/exercise1
. Change the name of the rulebook from "Example Rulebook" to "Listen for newly added PVC resources and create a snapshot".
. Update the `sources` section to use the appropriate source and watch for the proper Kubernetes objects. Replace `my_event_source` with the appropriate event source (`sabre1041.eda.k8s`). Replace `SomeResource` with `PersistentVolumeClaim`.
+
WARNING: The values are cap-sensitive. Ensure proper capitalization of `PersistentVolumeClaim`
+
[NOTE]
====
The event source _sabre1041.eda.k8s_ is a source module that enables the
consumption of changes originating from an OpenShift cluster which can then be
used to trigger automation to respond and act based on the received content and
configured rules.  
====
+
. Modify the rule named "Perform Action" to "Create Snapshot". Update the condition to create a snapshot when a Persistent Volume Claim is created via `event.type == "ADDED"`
. Change the name of the run_job_template from `Example-Job-Template` to `EDA-OpenShift-Exercise1`

=== Solution

.*Click to see solution*
[%collapsible]
====
[,yaml]
----
- name: Listen for newly added PVC resources and create a snapshot
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: PersistentVolumeClaim
  rules:
    - name: Create Snapshot
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: EDA-OpenShift-Exercise1
          organization: Default
----
====

==  Run the Ansible Rulebook

In order to run the Ansible Rulebook we will take advantage of the existing
quay.io Ansible Rulebook image that was pulled with in the prerequisites section
and make some slight modifications within the container.

. As the `lab-user` within your bastion host, change directory to the Git repository demos folder
+
----
$ cd /path/to/demos/eda_ocp/
----
+
. Capture the image ID of the Ansible Rulebook image
+
----
$ podman images
REPOSITORY                        TAG         IMAGE ID      CREATED      SIZE
quay.io/ansible/ansible-rulebook  v0.12.0     ddab79939a21  13 days ago  1.68 GB
----
+
. Start the ansible-rulebook container and access it. 
+
----
$ podman run -it --rm -v "$(pwd):/mnt:Z" --workdir /mnt --user 0 <IMAGE_ID> /bin/bash
----
+
. Within the ansible-rulebook container, run the `setup.sh`
+
----
(app-root) (app-root) ./setup.sh
----
+
[NOTE]
====
This installs pip packages `kubernetes`, `requests` and installs the
`sabre1041.eda` collection required for our Ansible Rulebook and Ansible
Playbook. It also installs the `oc` binary required to interactive with our
OpenShift cluster. 
====
+
. Login to your OpenShift cluster via
+
[source,subs="attributes"]
----
$ oc login --token={openshift_token} --server={openshift_api_url}
----
+
. Change to the `exercise_1` directory
+
[{format_cmd_exec}]
----
$ cd /mnt/exercise_1
----
. Run your Ansible Rulebook (`exercise1-rulebook.yml`) with your AAP controller credentials
+
[{format_cmd_exec}]
----
$ ansible-rulebook -i inventory --rulebook exercise1-rulebook.yml --verbose --controller-url {aap_controller_web_url} --controller-token {aap_controller_admin_token}
----
+
----
(app-root) (app-root) oc project default
Now using project "default" on server "https://api.cluster-8pqpx.8pqpx.sandbox2254.opentlc.com:6443".
(app-root) (app-root) ansible-rulebook -i inventory --rulebook pvc_snapshot_rulebook.yml --verbose
2023-04-25 16:13:19,351 - ansible_rulebook.app - INFO - Starting sources
2023-04-25 16:13:19,351 - ansible_rulebook.app - INFO - Starting rules
2023-04-25 16:13:19,351 - ansible_rulebook.engine - INFO - run_ruleset
2023-04-25 16:13:19,352 - drools.ruleset - INFO - Using jar: /opt/app-root/lib/python3.9/site-packages/drools/jars/drools-ansible-rulebook-integration-runtime-1.0.0-SNAPSHOT.jar
2023-04-25 16:13:20,269 - ansible_rulebook.engine - INFO - ruleset define: {"name": "Listen for newly added PVC resources and create a snapshot", "hosts": ["all"], "sources": [{"EventSource": {"name": "sabre1041.eda.k8s", "source_name": "sabre1041.eda.k8s", "source_args": {"api_version": "v1", "kind": "PersistentVolumeClaim"}, "source_filters": []}}], "rules": [{"Rule": {"name": "Create Snapshot", "condition": {"AllCondition": [{"EqualsExpression": {"lhs": {"Event": "type"}, "rhs": {"String": "ADDED"}}}]}, "actions": [{"Action": {"action": "run_playbook", "action_args": {"name": "pvc_snapshot_playbook.yml", "extra_vars": {"event": "{{ event }}"}}}}], "enabled": true}}]}
2023-04-25 16:13:20,291 - ansible_rulebook.engine - INFO - load source
2023-04-25 16:13:21,295 - ansible_rulebook.engine - INFO - load source filters
2023-04-25 16:13:21,295 - ansible_rulebook.engine - INFO - loading eda.builtin.insert_meta_info
2023-04-25 16:13:21,996 - ansible_rulebook.engine - INFO - Calling main in sabre1041.eda.k8s
2023-04-25 16:13:21,996 - root - INFO - Running k8s eda source
----

== Create the RocketChat App

With our Ansible Rulebook watching for an event, we will now create an
application that will trigger the Ansible Rulebook once a Persistent Volume
Claim is created.

. Open a new terminal window and ssh into the bastion host.
+
[{format_cmd_exec}]
----
$ ssh {bastion_ssh_user_name}@{bastion_public_hostname}
----
+
. Login using your token within this new terminal window.
+
[{format_cmd_exec}]
----
$ oc login --token={openshift_token} --server={openshift_api_url}
----
+
. Within the Git repository, access the /path/to/demos/eda_ocp/exercise_1 directory.
+
----
$ cd /path/to/demos/eda_ocp/exercise_1
----
+
. Create a namespace to host the RocketChat app
+
[{format_cmd_exec}]
----
$ oc project rocketchat
----
+
. Install the RocketChat App via the `app.yml` file
+
[{format_cmd_exec}]
----
$ oc create -f app.yml
----
+
. Once the PVC is bound to the application, this will trigger the Ansible Rulebook to run the Ansible Job `EDA-OpenShift-Exercise1` that will create a snapshot of the PVC.
+
. Looking at the terminal with the Ansible Rulebook container running you will see output similar to:
+
----
...
2023-04-26 19:05:21,598 - ansible_rulebook.builtin - INFO - running job template: EDA-OpenShift-Exercise1, organization: Default
2023-04-26 19:05:21,598 - ansible_rulebook.builtin - INFO - ruleset: Listen for newly added PVC resources and create a snapshot, rule Create Snapshot
----
+
. Once you see the Ansible Playbook has completed, verify the snapshot has been created. 
+
[{format_cmd_exec}]
----
$ oc get volumesnapshot -n rocketchat

NAME                             READYTOUSE   SOURCEPVC               SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS   SNAPSHOTCONTENT                                    CREATIONTIME   AGE
rocketchat-data-claim-snapshot-2023-04-26   true         rocketchat-data-claim                           10Gi          csi-aws-vsc     snapcontent-9db8e7f3-0d30-4777-8355-465b76d74de5   3h17m          3h17m
----
+
. Congratulations! You now have completed Exercise 1 of creating a PVC Snapshot upon application creation. 

== Expanding on this exercise

What else could you do with this Ansible Rulebook? 

One idea could be to add a scheduler to the PVC creation process where the
Ansible Playbook runs daily, weekly, monthly based on your compliance
requirements for your snapshots.


== Cleanup RocketChat App

As we will be using the RocketChat App for the next exercise, lets remove it as
we will be using it to trigger our next event relating SSL management.

To remove:

----
$ cd /path/to/eda_ocp/exercise_1
----


[{format_cmd_exec}]
----
$ oc delete -f app.yml
----
