---
- name: Create Let's Encrypt account key, SSL cert, and update OpenShift route
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.package:
        name:
          - python3-pyOpenSSL
        state: present

    - name: Generate an RSA private key for the Let's Encrypt account
      community.crypto.openssl_privatekey:
        path: /root/exercises/letsencrypt_account.key
        size: 2048

    - name: Create and register a Let's Encrypt account
      community.crypto.acme_account:
        account_key_src: /root/exercises/letsencrypt_account.key
        acme_version: 2
        state: present
        contact:
          - mailto:demo@myexample.com
        acme_directory: https://acme-v02.api.letsencrypt.org/directory
        terms_agreed: yes
      register: letsencrypt_account

    - name: Get Let's Encrypt account information
      community.crypto.acme_account_info:
        account_key_src: /root/exercises/letsencrypt_account.key
        acme_version: 2
        acme_directory: https://acme-v02.api.letsencrypt.org/directory
      register: letsencrypt_account_info

    - name: Display Let's Encrypt account information
      ansible.builtin.debug:
        var: letsencrypt_account_info

    - name: Generate a private key for my domain
      community.crypto.openssl_privatekey:
        path: /root/exercises/domain_private_key.pem
        size: 2048

    - name: Create a CSR for the domain
      community.crypto.openssl_csr:
        path: /root/exercises/domain.csr
        privatekey_path: /root/exercises/domain_private_key.pem
        common_name: rocket-chat-rocketchat.apps.rogerocp1.demoredhat.com

    - name: Create Let's Encrypt SSL certificate
      community.crypto.acme_certificate:
        account_key_src: /root/exercises/letsencrypt_account.key
        csr: /root/exercises/domain.csr
        dest: /root/exercises/cert.pem
        fullchain_dest: /root/exercises/fullchain.pem
        challenge: http-01
        acme_directory: https://acme-v02.api.letsencrypt.org/directory
        acme_version: 2
        account_email: demo@myexample.com
      register: cert_result

    - name: Update OpenShift route to use the new SSL certificate
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Route
          metadata:
            name: rocket-chat
            namespace: rocketchat
          spec:
            host: rocket-chat-rocketchat.apps.rogerocp1.demoredhat.com
            to:
              kind: Service
              name: rocket-chat
              weight: 100
            port:
              targetPort: 3000
            wildcardPolicy: None
            tls:
              termination: edge
              key: "{{ lookup('file', '/root/exercises/domain_private_key.pem') }}"
              certificate: "{{ lookup('file', '/root/exercises/cert.pem') }}"
              caCertificate: "{{ lookup('file', '/root/exercises/fullchain.pem') }}"
