---
- name: Deploy Resources to OpenShift
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create rocketchat Namespace
      kubernetes.core.k8s:
        kind: Namespace
        name: rocketchat
        state: present

    - name: Apply Kubernetes Resources
      kubernetes.core.k8s:
        src: "{{ item }}"
        namespace: rocketchat
      loop:
        - demos/backstage-aap/rocketchat/1-pvc.yml
        - demos/backstage-aap/rocketchat/2-deployment-mongo.yml
        - demos/backstage-aap/rocketchat/3-service-mongo.yml
        - demos/backstage-aap/rocketchat/4-deployment-rocket.yml
        - demos/backstage-aap/rocketchat/5-service-rocket.yml
        - demos/backstage-aap/rocketchat/6-route.yml

    - name: Pause for a short duration after each resource application
      pause:
        seconds: 15
      loop:
        - demos/backstage-aap/rocketchat/1-pvc.yml
        - demos/backstage-aap/rocketchat/2-deployment-mongo.yml
        - demos/backstage-aap/rocketchat/3-service-mongo.yml
        - demos/backstage-aap/rocketchat/4-deployment-rocket.yml
        - demos/backstage-aap/rocketchat/5-service-rocket.yml
        - demos/backstage-aap/rocketchat/6-route.yml

