---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: Retrieve a repository from a distant location and make it available locally
      ansible.scm.git_retrieve:
        origin:
          url: https://github.com/rlopez133/demos.git
      register: repository

    - name: Create rocketchat Namespace
      kubernetes.core.k8s:
        kind: Namespace
        name: rocketchat
        state: present

    - name: Apply Kubernetes Resources
      kubernetes.core.k8s:
        src: "{{ repository.path }}/backstage-aap/rocketchat/{{ item }}"
        namespace: rocketchat
      loop:
        - 1-deployment-mongo.yml
        - 2-deployment-rocket.yml
        - 3-pvc.yml
        - 4-route.yml
        - 5-service-mongo.yml
        - 6-service-rocket.yml
