---
- name: Create ReplicationSource
  hosts: localhost
  become: yes
  gather_facts: no

  tasks:
  - name: Create ReplicationSource
    kubernetes.core.k8s:
      state: present
      namespace: "{{ my_namespace }}"
      definition:
        apiVersion: volsync.backube/v1alpha1
        kind: ReplicationSource
        metadata:
          name: "{{ my_name }}"
        spec:
          sourcePVC: "{{ source_pvc }}"
          trigger:
            schedule: "*/30 * * * *"
          restic:
            pruneIntervalDays: 14
            repository: "{{ repo }}"
            retain:
              hourly: "{{ hourly }}"
              daily: "{{ daily }}"
              weekly: "{{ weekly }}"
              monthly: "{{ monthly }}"
              yearly: "{{ yearly }}"
            copyMethod: Snapshot
