---

- name: Notify Slack that EC2 instance has been created
  community.general.slack:
    token: "{{ token }}"
    msg: |
        ```
        #### EC2 Instance for {{ paths['instances[0].tags.owner'] }} ####
        ----------------------------------------------------
        Name: {{ paths['instances[0].tags.Name'] }}
        Public IP: {{ paths['instances[0].public_ip_address'] }}
        
        Login using your private key:
        ssh -i /path/to/private_key ec2-user@{{ paths['instances[0].public_ip_address'] }}

        Need Assistance?
        <https://example.com|Open a ticket>
        ----------------------------------------------------
        ```
    channel: '#ansiblefest-demo'
    color: good
    username: 'AnsibleFest-bot'
    link_names: 0
    parse: 'none'
