{
 "title": "Automation Controller Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "License & Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tower Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "awx_system_info" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(awx_instance_info)", "legendFormat": "Total" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "awx_license_instance_total", "legendFormat": "Total de Licenças" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(awx_license_instance_total - awx_license_instance_free)"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "awx_users_total", "legendFormat": "Total" },
    {
     "expr": "count(awx_sessions_total{type=\"user\"})",
     "legendFormat": "Users"
    },
    {
     "expr": "count(awx_sessions_total{type=\"anonymous\"})",
     "legendFormat": "Anonymous"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "awx_status_total{status=\"successful\"}",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "awx_status_total{status=\"failed\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(awx_instance_launch_type_total{launch_type=\"dependency\"})",
     "legendFormat": "Dependency"
    },
    {
     "expr": "sum(awx_instance_launch_type_total{launch_type=\"manual\"})",
     "legendFormat": "Manual"
    },
    {
     "expr": "sum(awx_instance_launch_type_total{launch_type=\"relaunch\"})",
     "legendFormat": "Relaunch"
    },
    {
     "expr": "sum(awx_instance_launch_type_total{launch_type=\"scheduled\"})",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "sum(awx_instance_launch_type_total{launch_type=\"workflow\"})",
     "legendFormat": "Workflow"
    }
   ]
  },
  {
   "title": "Job Running",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(rate(awx_running_jobs_total[1m] offset 1d))",
     "legendFormat": "Last day"
    },
    { "expr": "awx_running_jobs_total[1d]", "legendFormat": "Actual" }
   ]
  },
  {
   "title": "Job Pending",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(rate(awx_pending_jobs_total[1m] offset 1d))",
     "legendFormat": "Last day"
    },
    { "expr": "awx_pending_jobs_total[1d]", "legendFormat": "Actual" }
   ]
  },
  {
   "title": "Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "awx_job_templates_total", "legendFormat": "Job Templates" },
    { "expr": "awx_inventories_total", "legendFormat": "Inventories" },
    { "expr": "awx_projects_total", "legendFormat": "Projects" },
    { "expr": "awx_organizations_total", "legendFormat": "Organizations" },
    {
     "expr": "awx_hosts_total{type=\"active\"}",
     "legendFormat": "Active Hosts"
    },
    { "expr": "awx_teams_total", "legendFormat": "Teams" },
    {
     "expr": "awx_workflow_job_templates_total",
     "legendFormat": "Workflow  Job Templates"
    }
   ]
  }
 ]
}