---
- name: Ansible Playbook for PVC and VolumeSnapshot
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Block to handle PVC and VolumeSnapshot
      block:
        - name: Wait for Persistent Volume Claim to be Bound
          kubernetes.core.k8s_info:
            kind: PersistentVolumeClaim
            namespace: "{{ event.resource.metadata.namespace }}"
            name: "{{ event.resource.metadata.name }}"
          register: pvc_status
          until: pvc_status.resources[0].status.phase == "Bound"
          retries: 30
          delay: 2

        - name: Create VolumeSnapshot
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: snapshot.storage.k8s.io/v1
              kind: VolumeSnapshot
              metadata:
                name: "{{ event.resource.metadata.name }}-snapshot"
                namespace: "{{ event.resource.metadata.namespace }}"
              spec:
                source:
                  persistentVolumeClaimName: "{{ event.resource.metadata.name }}"
          when: pvc_status.resources[0].status.phase == "Bound"

      rescue:
        - name: Handle PVC not Bound
          ansible.builtin.debug:
            msg: "Status 'Bound' was never achieved for the Persistent Volume Claim {{ event.resource.metadata.name }}"
