- name: Listen for newly added PVC resources
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: PersistentVolumeClaim
  rules:
    - name: Notify
      condition: event.type == "ADDED"
      action:
          debug: 
