:bastion_ssh_user_name: %bastion_ssh_user_name%
:bastion_public_hostname: %bastion_public_hostname%
:aap_controller_web_url: %aap_controller_web_url%
:aap_controller_admin_user: %aap_controller_admin_user%
:aap_controller_admin_password: %aap_controller_admin_password%
:aap_controller_admin_token: %aap_controller_admin_token%
:openshift_api_url: %openshift_api_url%
:openshift_token: %openshift_token%
:format_cmd_exec: source,options="nowrap",,role="copy",subs="{markup-in-source}"

== Configuring Namespace Resource Quotas with Ansible Playbooks

As organizations grow and multiple projects, teams, or applications share the
same OpenShift cluster, it becomes essential to manage and allocate resources
fairly and efficiently. This ensures that a single namespace cannot monopolize
the available resources, potentially causing performance issues and reducing
resources available for other namespaces.

In this exercise, you will create an Ansible Rulebook that triggers an Ansible
Job Template to set up resource quotas when a namespace is created in an
OpenShift cluster.

You will work with an Ansible playbook that performs the following tasks:

*  Sets resource quotas for the namespace (CPU and memory requests and limits) 
* Verifies the resource quotas applied to the namespace 

Your objective is to develop an Ansible Rulebook that activates this Ansible
playbook through an Ansible Job Template within the automation controller.

== Prerequisites

* Access to your Bastion Host Credentials
* Access to your controller admin token
* Access to the automation controller dashboard
* SSH capabilities to the Bastion Host via terminal

NOTE: The Prerequisites details can all be found within the Overview section.

== Understanding the Provided Ansible Playbook

This Ansible playbook is specifically designed to set resource quotas for a
OpenShift namespace, ensuring fair and efficient distribution of resources
across namespaces in a OpenShift cluster. Resource quotas play a vital role in
preventing a single namespace from monopolizing resources and causing
performance issues.

The `kubernetes.core.k8s` module is used to set the resource quotas, enabling
efficient management of resources allocated to different projects, teams, or
applications within the OpenShift cluster.

The following is a breakdown of the tasks being performed by the Ansible
playbook:

* *Define variables:* The playbook starts by defining various variables required for the configuration process. These include the namespace (`ns`), CPU and memory requests (`requests_cpu` and `requests_memory`), and CPU and memory limits (`limits_cpu` and `limits_memory`). These variables make it easy to adjust resource quotas for different quota requirements.

* *Set resource quotas:* The single task in the playbook sets the resource quotas using the `kubernetes.core.k8s` module. This module creates or updates a ResourceQuota object in the specified namespace, with the resource limits and requests defined by the variables. By using this module, the playbook can efficiently set resource quotas for a Openshift namespace, ensuring fair allocation of resources in the cluster.

.Ansible Resource Management Playbook
----
---
- name: Set resource quotas for a Kubernetes cluster for a namespace
  hosts: localhost
  gather_facts: no
  vars:
    ns: "{{ ansible_eda.event.resource.metadata.namespace }}"
    requests_cpu: '1'
    limits_cpu: '2'
    requests_memory: '1Gi'
    limits_memory: '2Gi'
    
  tasks:
    - name: Set resource quotas
      kubernetes.core.k8s:
        api_version: v1
        kind: ResourceQuota
        namespace: "{{ ns }}"
        name: resource-quota
        state: present
        definition:
          spec:
            hard:
              limits.cpu: "{{ limits_cpu }}"
              limits.memory: "{{ limits_memory }}"
              requests.cpu: "{{ requests_cpu }}"
              requests.memory: "{{ requests_memory }}"

----

== Writing the Ansible Rulebook

In this section, you will be provided with an example rulebook. Your task is to
modify the example rulebook to run the Ansible Job Template
`EDA-OpenShift-Exercise3` when a `Namespace` gets created.

[{format_cmd_exec}]
.Example Rulebook
----
- name: Example Rulebook
  hosts: all
  sources:
    - my_event_source:
        api_version: v1
        kind: SomeResource
  rules:
    - name: Perform Action
      condition: event.type == "SOME_EVENT"
      action:
        run_job_template:
          name: Example-Job-Template
          organization: Default
----

Follow these steps to modify the example rulebook:

. Copy the example rulebook to a file named `exercise3-rulebook.yml` within the `/home/lab-user/demos/eda_ocp/exercise_3` directory.
+
[NOTE]
====
Using the `vi` editor, to ensure that the formating of the pasted content is
preserved, enter command mode by pressing the `Esc` key and type the following
`:set paste` followed by enter. Then insert the content at the current cursor
position by pressing the `i` key to enter insert mode.
====
+
. Change the name of the rulebook from `Example Rulebook` to `Listen for newly created Namespace`.
. Update the `sources` section to use the appropriate source and watch for the
proper Kubernetes objects. Replace `my_event_source` with the appropriate event source (`sabre1041.eda.k8s`). Replace `SomeResource` with `Namespace`.
+
WARNING: The values are cap-sensitive. Ensure proper capitalization of `Namespace`
+
[NOTE]
====
The event source _sabre1041.eda.k8s_ is a source module that enables the
consumption of changes originating from an OpenShift cluster which can then be
used to trigger automation to respond and act based on the received content and
configured rules.
====
+
. Modify the rule named `Perform Action` to `Set Resource Quotas to  a Namespace`. Update the condition to create resource quotas when a Namespace is created via `event.type == "ADDED"`
. Change the name of the run_job_template from `Example-Job-Template` to `EDA-OpenShift-Exercise3`
. Save your changes within the `vi` editor by entering command mode by pressing the `Esc` key and typing `:wq` followed by the Enter key.

WARNING: Ensure that your job template name matches `EDA-OpenShift-Exercise3`

=== Solution

.*Click to see solution*
[%collapsible]
====
[,yaml]
----
- name: Listen for newly created Namespace
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: Namespace
  rules:
    - name: Set Resource Quotas to a Namespace
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: EDA-OpenShift-Exercise3
          organization: Default
----
====

NOTE: Feel free to compare your solution with the provided solution found within
the exercise.

==  Run the Ansible Rulebook

In order to run the Ansible Rulebook we will take advantage of the existing
quay.io Ansible Rulebook image that was pulled in exercise 1.

[NOTE]
====
Within the top terminal window, if you are still connected to the bastion host
and within the Ansible Rulebook container, `Ctrl-C` to stop the Ansible Rulebook
command running from Exercise 1. Steps 1-5 may be skipped.

Otherwise continue with the steps as provided to create a new container.
====

. As the `lab-user` within your bastion host, change directory to the Git repository demos folder
+
----
$ cd /home/lab-user/demos/eda_ocp/
----
+
. Capture the image ID of the Ansible Rulebook image
+
----
podman images
REPOSITORY                        TAG         IMAGE ID      CREATED      SIZE
quay.io/ansible/ansible-rulebook  v0.12.0     ddab79939a21  13 days ago  1.68 GB
----
+
. Start the ansible-rulebook container and access it.
+
----
podman run -it --rm -v "$(pwd):/mnt:Z" --workdir /mnt --user 0 <IMAGE_ID> /bin/bash
----
+
. Within the ansible-rulebook container, run the `setup.sh`
+
----
(app-root) (app-root) ./setup.sh
----
+
[NOTE]
====
This installs pip packages `kubernetes`, `requests` and installs the
`sabre1041.eda` collection required for our Ansible Rulebook and Ansible
Playbook. It also installs the `oc` binary required to interactive with our
OpenShift cluster.
====
+
. Login to your OpenShift cluster via
+
[{format_cmd_exec}]
----
oc login --token={openshift_token} --server={openshift_api_url}
----
+
[NOTE]
====
Accept the Use insecure connections check.
====
+
. Change to the `exercise_3` directory
+
[{format_cmd_exec}]
----
cd /mnt/exercise_3
----
. Run your Ansible Rulebook (`exercise3-rulebook.yml`) with your Ansible automation controller credentials
+
[{format_cmd_exec}]
----
ansible-rulebook -i inventory --rulebook exercise3-rulebook.yml --verbose --controller-url {aap_controller_web_url} --controller-token {aap_controller_admin_token}
----
+
----
2023-05-09 16:31:37,295 - ansible_rulebook.app - INFO - Starting sources
2023-05-09 16:31:37,295 - ansible_rulebook.app - INFO - Starting rules
2023-05-09 16:31:37,295 - ansible_rulebook.engine - INFO - run_ruleset
2023-05-09 16:31:37,296 - drools.ruleset - INFO - Using jar: /opt/app-root/lib/python3.9/site-packages/drools/jars
/drools-ansible-rulebook-integration-runtime-1.0.0-SNAPSHOT.jar
2023-05-09 16:31:38,262 - ansible_rulebook.engine - INFO - ruleset define: {"name": "Listen for newly created Name
space", "hosts": ["all"], "sources": [{"EventSource": {"name": "sabre1041.eda.k8s", "source_name": "sabre1041.eda.
k8s", "source_args": {"api_version": "v1", "kind": "Namespace"}, "source_filters": []}}], "rules": [{"Rule": {"nam
e": "Set Resource Quotas to  a Namespace", "condition": {"AllCondition": [{"EqualsExpression": {"lhs": {"Event": "
type"}, "rhs": {"String": "ADDED"}}}]}, "actions": [{"Action": {"action": "run_job_template", "action_args": {"nam
e": "EDA-OpenShift-Exercise3", "organization": "Default"}}}], "enabled": true}}]}
2023-05-09 16:31:38,282 - ansible_rulebook.engine - INFO - load source
2023-05-09 16:31:39,310 - ansible_rulebook.engine - INFO - load source filters
2023-05-09 16:31:39,310 - ansible_rulebook.engine - INFO - loading eda.builtin.insert_meta_info
2023-05-09 16:31:40,010 - ansible_rulebook.engine - INFO - Calling main in sabre1041.eda.k8s
2023-05-09 16:31:40,011 - root - INFO - Running k8s eda source
----

//TODO create setps to trigger Rulebook and fix output

. Create a namespace
+
. Looking at the top terminal window with the Ansible Rulebook container running you will see output similar to:
+
----
...
2023-05-09 16:33:05,144 - ansible_rulebook.rule_set_runner - INFO - action args: {'name': 'EDA-OpenShift-Exercise3
', 'organization': 'Default'}
2023-05-09 16:33:05,144 - ansible_rulebook.builtin - INFO - running job template: EDA-OpenShift-Exercise3, organiz
ation: Default
2023-05-09 16:33:05,144 - ansible_rulebook.builtin - INFO - ruleset: Listen for newly created Namespace, rule Set
Resource Quotas to  a Namespace
----
+
. Head toward your browser with the Ansible Automation Platform dashboard and login (if not already). Within the dashboard, select `Views->Jobs` and you will see the `EDA-OpenShift-Exercise3` job is launched and running.
+
. Once you see the Ansible Job has completed successfully, verify the resource quota of the created namespace.
+
[{format_cmd_exec}]
----
$ oc get resourcequota-n <namespace>
NAME             AGE   REQUEST                                     LIMIT
resource-quota   60s   requests.cpu: 0/1, requests.memory: 0/1Gi   limits.cpu: 0/2, limits.memory: 0/2Gi
----

== Verify the resource quota


To test the resource quotas using the `oc` command-line tool, you can create a
simple pod that requests and consumes more resources than allowed by the
resource quotas.

Let's first create a simple pod manifest file named test-pod.yml:

----
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: test-container
      image: busybox
      command: ["sh", "-c", "while true; do echo 'Resource test'; sleep 10; done"]
      resources:
        requests:
          cpu: 1.5
          memory: 1.5Gi
        limits:
          cpu: 2.5
          memory: 2.5Gi
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop: ["ALL"]
----

This pod definition has a single container that requests 1.5 CPU and 1.5Gi
memory, and sets limits of 2.5 CPU and 2.5Gi memory. These values exceed the
resource quotas defined in the previous example (1 CPU and 1Gi for requests, and
2 CPUs and 2Gi for limits).

Attempt to create the pod via:

----
oc create -f test-pod.yml -n <namespace>
----

And it should provide the following error:

----
Error from server (Forbidden): error when creating "test-pod.yml": pods "test-pod" is forbidden: exceeded quota:
resource-quota, requested: limits.cpu=2500m,limits.memory=2560Mi,requests.cpu=1500m,requests.memory=1536Mi, used:
limits.cpu=0,limits.memory=0,requests.cpu=0,requests.memory=0, limited: limits.cpu=2,limits.memory=2Gi,requests.cp
u=1,requests.memory=1Gi
----

Re-attempting with values that reside within the requests and limit values
should reside in proper creation of the test pod. For example, setting the
request values to 1 cpu, 1Gi of memory, while setting the limits to 2 cpu and
2Gi of memory will result in a successful creation of the pod.

----
oc create -f test-pod.yml -n <namespace>
----

----
pod/test-pod created
----

== Summary

In this exercise, you learned how to automatically set resource quotas for a
newly created namespace within your OpenShift cluster using Ansible Rulebooks.

You learned how to:

. Write an Ansible Rulebook that listens for newly created Namespaces and adds resource quotas based upon the resource requests and resource limits set within your Ansible playbook.
. Understand the provided Ansible playbook, which leverages the kubernetes.core module to set resource quotas enabling efficient management of resources allocated across different projects and teams.
. Run the Ansible Rulebook using the quay.io Ansible Rulebook image.
. Verify that the Namespace contains the resource quotas and that are properly set.
