- name: Listen for newly added PVC resources and create a snapshot
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: PersistentVolumeClaim
  rules:
    - name: Create Snapshot
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: EDA-OpenShift-Exercise1
          organization: Default
